### ISSUE TITLE
IOError: 5

### ISSUE THREAD

**Issue by ghost** [DFRobot/DFRobot_ADS1115#1]
When i run ADS1115_ReadVoltage.py on my Raspberry Pi 3B+ i get the following error:

Traceback (most recent call last):
  File "func_ADC_ReadVoltage.py", line 19, in <module>
    adc0 = ads1115.readVoltage(0)
  File "/home/pi/apps/smartgarden/_functions/DFRobot_ADS1115.py", line 142, in readVoltage
    self.setSingle()
  File "/home/pi/apps/smartgarden/_functions/DFRobot_ADS1115.py", line 110, in setSingle
    bus.write_i2c_block_data(addr_G, ADS1115_REG_POINTER_CONFIG, CONFIG_REG)
  File "/usr/local/lib/python2.7/dist-packages/smbus/util.py", line 59, in validator
    return fn(*args, **kwdefaults)
  File "/usr/local/lib/python2.7/dist-packages/smbus/smbus.py", line 275, in write_i2c_block_data
    raise IOError(ffi.errno)
IOError: 5

**Comment by ghost** [comment]
?

**Comment by qsjhyy** [comment]
Hello, communication IO port problem may be poor pin contact
